# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d28affec8a086bc92c339f6eb28e583b5c7241af384f143d128fcfba5488a750c99af06f543d8bf24c51fe1e231a16a888651fe17b449ee64c2239af557a903c

test:
  secret_key_base: 28cd1e7edb75225e5c0be8777a4fd756929a0c964fe43891dd48ad410b2e6c8adbc0a923b1e8a9b62fbbb9b9ffc2e828c55f8d4d47a0c01f039a9c5088cb6a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
